### ISSUE TITLE
是否可以支持写入io.Writer里?

### ISSUE THREAD

**Issue by schooltech** [tiechui1994/gopdf#14]
你好，是否可以支持写入io.Writer里?这样的话，可以直接写入浏览器的缓存了，就越过写pdf文件而直接在浏览器打开。
谢谢

**Comment by tiechui1994** [comment]
> 你好，是否可以支持写入io.Writer里?这样的话，可以直接写入浏览器的缓存了，就越过写pdf文件而直接在浏览器打开。
> 谢谢

你指的是直接将PDF输出的内容输出到一个一个Writer当中, 是这个意思吗?

**Comment by schooltech** [comment]
是的，将pdf内容，写入io.Writer

**Comment by schooltech** [comment]
可以的，我看到里面有个GetBytesPdf方法
