### ISSUE TITLE
panic: font file:ttf//microsoft.ttf not found 请问怎么解决

### ISSUE THREAD

**Issue by liqiangxuMr** [tiechui1994/gopdf#21]
panic: font file:ttf//microsoft.ttf not found

**Comment by tiechui1994** [comment]
use absolute ttf path

**Comment by liqiangxuMr** [comment]
the problem resolved，thank you very much！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: quinn <notifications@github.com&gt;
发送时间: 2020年6月21日 19:49
收件人: tiechui1994/gopdf <gopdf@noreply.github.com&gt;
抄送: liqiangxu@han <1249782650@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tiechui1994/gopdf] panic: font file:ttf//microsoft.ttf not found 请问怎么解决 (#21)
