### ISSUE TITLE
Hi， 报异常哦。可以删掉该字段哦

### ISSUE THREAD

**Issue by DyncMing** [tiechui1994/gopdf#22]
![image](https://user-images.githubusercontent.com/16282330/87872408-c30a8c00-c9ea-11ea-8d6a-79ad05eade36.png)

**Comment by DyncMing** [comment]
../../pkg/mod/github.com/tiechui1994/gopdf@v0.0.0-20200713122355-d3d28cb2b69c/mdtext.go:202:3: lastStep declared but not used

**Comment by tiechui1994** [comment]
markdown 分支是目前在开发的 markdown 转 PDF, 目前还处于开发阶段, 该分支目前不能正常使用
