### ISSUE TITLE
跨页空页问题

### ISSUE THREAD

**Issue by researchlab** [tiechui1994/gopdf#8]
在测试使用过程中，发现当报告生成页数超过15页后， 在第15页会存在大版空页，是的前后内容中间空出来一大片， 这个是什么原因？

目前的解决方法是将第15页的内容 强制设置一个比较大的div top值， 使得15页直接全部留空， 不知道是不是因为使用的格式问题还是页面超过15页导致的这个问题

**Comment by tiechui1994** [comment]
目前正在思考span和div的margin和border问题, 这个问题的解决可能帮助解决你说的问题

**Comment by tiechui1994** [comment]
问题已经解决. 关于span的问题, 通过设置margin和border进行解决.
